### ISSUE TITLE
Change 'viewbox' to 'viewBox' in transform.py

### ISSUE THREAD

**Issue by SarangKulkarni** [btel/svg_utils#19]
In the height and width setters in transform.py, shouldn't `viewbox` read `viewBox`?

[https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox](https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox)
clearly shows the correct name to be `viewBox`.

This matters particularly for old browsers which do not understand `viewbox` but do understand `viewBox`.

**Comment by btel** [comment]
You are right. I have not realised that svg attributes are case-sensitive.
