### ISSUE TITLE
Update PIP package

### ISSUE THREAD

**Issue by brghena** [btel/svg_utils#22]
The pip package for `svg_utils` was last updated over a year ago, and there have been a number of helpful commits since then. Is there anything holding back another release?

**Comment by btel** [comment]
Hi, thanks for the message. Indeed, a new release is long overdue. At present there is a long backlog of the unsolved issues. As soon as they are all fixed, I will create a new release.

**Comment by btel** [comment]
Version 0.3.0 of svgutils has just been released. Thanks for your contribution!

**Comment by brghena** [comment]
Thanks for the update!

**Comment by bobatsar** [comment]
hey @btel  the package is again very outdated, can you publish a new one to pip?

**Comment by btel** [comment]
thanks for reporting @bobatsar. Indeed, the pip package was very outdated. It should be good now.

**Comment by bobatsar** [comment]
Wow that was fast. Thanks a lot.
