### ISSUE TITLE
scale_xy() from compose not working

### ISSUE THREAD

**Issue by Virtex7** [btel/svg_utils#28]
I need advice or an example for the method scale_xy() from svgutils.compose.

when I try to use it like this i get the following error:

sc.Figure("12cm", "12cm", 
		  sc.Panel(sc.SVG("./test1.svg").scale_xy(0.558, 0.559)),
		  ).save("./ergebnis.svg")

ERRORS:
Argument 'element' has incorrect type (expected lxml.etree._Element, got NoneType)

also the fallback that should be scaling within on axis doesnt work as well, it brings up the following error:
TypeError: must be real number, not str

I used a simple .scale_xy(1) as number, not even something with a fractional number..

actually i'm done with it :/ and can not find the clue...

if someone would help out or say that i'm trying it right that would be nice.

greetings,
Philipp

**Comment by shervinsahba** [comment]
This issue can most likely be closed since merging #55.

**Comment by btel** [comment]
Closing. Thanks @shervinsahba
