### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by btel** [btel/svg_utils#49]
## What

To nurish supportive  community, we need a inclusive code of coduct and a way to enforce it.

## How

* look for existing code of conducts from thriving open source communities
* describe a way of enforcing the code of conduct and the first contact person in case of any issues
* add CODE_OF_CONDUCT.rst file and add it to the repository

**Comment by Jam-Iko** [comment]
I would like to take this issue. Please assign it to me.
Also, who should be listed as a person of contact for second task?

**Comment by btel** [comment]
Hey @Jam-Iko, thanks for volunteering. 

For the person of contact, we should choose someone from the community. We might ask for volunteers in the comments to this issue. Would you like to do it?

**Comment by Jam-Iko** [comment]
@btel thank you assigning this issue to me. 
As for being the person of contact, I don’t know yet if I would make a good enforcer ))) 
Let’s ask for volunteers.
