### ISSUE TITLE
add instructions for conda

### ISSUE THREAD

**Issue by btel** [btel/svg_utils#50]
## what

svgutils can be installed with pip, but also with conda. For now, the docs only cover installation with pip. Add instructions for installing with conda (from conda-forge channel)

## how

* add instructions to README (something like `conda install svgutils -c conda-forge`
* add getting started section to sphinx documentation with installation instructions
   - you will need to add a new file getting_started.rst
   - and link to it in the index.rst (https://github.com/btel/svg_utils/blob/master/docs/source/index.rst)
 
check PR #45 for further links on editting sphinx docs

**Comment by khushishikhu** [comment]
may i work on this

**Comment by btel** [comment]
sure go ahead! let me know if you need any help. Thanks for volunteering!

**Comment by khushishikhu** [comment]
@btel  please have a look on my PR

**Comment by btel** [comment]
sure @khushishikhu. I just added a comment. Thanks for contributing!

**Comment by khushishikhu** [comment]
@btel  i have made the required changes that you asked for. please review my PR

**Comment by btel** [comment]
closed  by PR #51
