### ISSUE TITLE
save method creates a blank svg

### ISSUE THREAD

**Issue by shervinsahba** [btel/svg_utils#53]
The following code outputs the desired plot in Jupyter Lab, but the saved graphic is blank.

```
sc.Figure("18cm", "9cm",
    sc.Panel(
       sc.SVG("fig1"),
       sc.Text("A", 8, 18, size=14, font='sans')
    ),
    sc.Panel(
       sc.SVG("fig2"),
       sc.Text("B", 8, 18, size=14, font='sans')
    )
).save('test')
```

**Comment by btel** [comment]
thanks @shervinsahba, it works with the examples that I have. It's probably something about the input files that causes the problem. Would you mind sharing fig1, fig2 and test (output file)? If you don't want to share them pubilcly, you can share it with my by a private message on [gitter](https://gitter.im/svg_utils)

**Comment by shervinsahba** [comment]
Thanks for the reply @btel. Looks like it works overall! There may or may not be an issue with the default SVG encoding produced by svgutils, since several programs seemed to not render the image (see below). I experienced the issue with a variety of files including the [example SVG logo](https://github.com/btel/svg_utils/blob/master/examples/files/svg_logo.svg?short_path=6acae67).

- Krita reads in the outputted SVG as a blank image but works fine with the originals.
- Thunar file manager does not display a thumbnail for the outputted SVG but does for the originals.
- Inkscape worked fine.
- Firefox worked fine.

But, wow, now that this works I need to say thanks! This really helps with the figures workflow.

**Comment by btel** [comment]
thanks @shervinsahba for reporting, we need to work more on standard conformity and compatibility with all the viewers. I am glad to hear that you find svg_utils useful!
