### ISSUE TITLE
0.3.1 wheel upload "svgutils-0.3.1-py3-none-any.whl" of 2010-01-04 is not 0.3.1 and breaks existing software

### ISSUE THREAD

**Issue by hartwork** [btel/svg_utils#59]
Hi!

I'm a happy user of  `svgutils` with my CLI tool [xiangqi-setup](https://github.com/hartwork/xiangqi-setup); thank you for developing and sharing it as Open Source (or Software Libre) :pray: 

I have an [explicit `svgutils==0.3.1` in my setup.py file](https://github.com/hartwork/xiangqi-setup/blob/c846ec985ac9998d939651ad5b8b44c50432d042/setup.py#L44) (due to API incompatible changes on Git master after 0.3.1, which I accept and which are not my concern here). Today I noticed that CI started failing with 0.3.1 and it turns out that a new wheel `svgutils-0.3.1-py3-none-any.whl` was upload for 0.3.1 that **contains post-0.3.1 code**, see https://pypi.org/project/svgutils/0.3.1/#files. I'll be working on migrating my code to 0.3.2 shortly but I can only fix it for *future* releases. Could you delete that wheel file please to unbreak past and current releases of existing software depending on  `svgutils==0.3.1`? Thanks in advance! :pray: 

Best, Sebastian

**Comment by esc** [comment]
@btel hi Bartosz, @hartwork brought be me here, just wanted to say: "Hi! long time no see! Hope you are well and safe! " Feel free to delete this comment to retain signal-to-noise ratio on this issue. 😘

**Comment by btel** [comment]
Hi @hartwork, thanks for reporting. This must have happened during releasing 0.3.2. I will fix it tonight.

**Comment by hartwork** [comment]
Thank you!

**Comment by btel** [comment]
I just deleted the wheel, which was uploaded by mistake. Could you check whether it fixes the problem on your side?

**Comment by hartwork** [comment]
Seems so, yes, re-running the same CI job that failed previously yields success now. Thank you!
