### ISSUE TITLE
Plans for dropping support for end-of-life Python 2.7 and 3.5?

### ISSUE THREAD

**Issue by hartwork** [btel/svg_utils#66]
Hi!

The oldest version of Python that has *not* [reached end of life](https://endoflife.date/python) as of today is Python 3.6. The svgutils code base currently supports 2.7 and 3.5 officially and in practice. I have seen people have vastly different opinions on which versions of Python should be supported by a project in 2021, before. So I would just like to hear what the current plan or approach about end-of-life Python is, and then see how and if I can help.
A benefit of dropping support for old versions, is that we could e.g. start using [f-strings](https://www.python.org/dev/peps/pep-0498/) and [type hints](https://docs.python.org/3/library/typing.html) in this code base if we wanted, in general.

Best, Sebastian

**Comment by btel** [comment]
sure, I am fine with dropping Python 2.x or even <=3.5 in 0.4.0. Especially if some features of >3.5 will be useful in the code base.

**Comment by hartwork** [comment]
Okay, I'll prepare a pull request in a minute.
