### ISSUE TITLE
SVGFigure does not set width and height element if created directly

### ISSUE THREAD

**Issue by akhmerov** [btel/svg_utils#89]
Width and height aren't correctly set in the XML if `transform.SVGFigure` is created directly:

```python
import svgutils
svgutils.transform.SVGFigure("10cm", "16cm").to_str()
```
prints 
```python
b'<?xml version=\'1.0\' encoding=\'ASCII\' standalone=\'yes\'?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"/>\n'
```
This code is used in the tutorial:

https://github.com/btel/svg_utils/blob/4abf7fb18cea0da04b6b2a0bcacbec5daded1662/docs/source/tutorials/scripts/fig_final.py#L5

Therefore I expect that this is not an intended behavior.

**Comment by hartwork** [comment]
Hi @akhmerov, which version (or Git commit) of svgutils is this about?

**Comment by Knochi** [comment]
same here

**Comment by myzonexu** [comment]
I think the problem is here:
transform.py  line:259,271
**value.value**
It works when the value use Unit(),but not work when use int or string
 @width.setter
    def width(self, value):
        self._width = **value.value**
        self.root.set("width", str(value))
        self.root.set("viewBox", "0 0 %s %s" % (self._width, self._height))

**Comment by btel** [comment]
indeed we don't set the SVG tag attributes when width or height is an integer/string
